<?php
/**
 * ApiEmailConfiguration
 *
 * PHP version 5
 *
 * @category Class
 * @package  Optimacros\NexusPhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.43.0-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Optimacros\NexusPhpApi\Model;

use \ArrayAccess;
use \Optimacros\NexusPhpApi\ObjectSerializer;

/**
 * ApiEmailConfiguration Class Doc Comment
 *
 * @category Class
 * @package  Optimacros\NexusPhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ApiEmailConfiguration implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ApiEmailConfiguration';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'enabled' => 'bool',
        'host' => 'string',
        'port' => 'int',
        'username' => 'string',
        'password' => 'string',
        'fromAddress' => 'string',
        'subjectPrefix' => 'string',
        'startTlsEnabled' => 'bool',
        'startTlsRequired' => 'bool',
        'sslOnConnectEnabled' => 'bool',
        'sslServerIdentityCheckEnabled' => 'bool',
        'nexusTrustStoreEnabled' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'enabled' => null,
        'host' => null,
        'port' => 'int32',
        'username' => null,
        'password' => null,
        'fromAddress' => null,
        'subjectPrefix' => null,
        'startTlsEnabled' => null,
        'startTlsRequired' => null,
        'sslOnConnectEnabled' => null,
        'sslServerIdentityCheckEnabled' => null,
        'nexusTrustStoreEnabled' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'enabled' => 'enabled',
        'host' => 'host',
        'port' => 'port',
        'username' => 'username',
        'password' => 'password',
        'fromAddress' => 'fromAddress',
        'subjectPrefix' => 'subjectPrefix',
        'startTlsEnabled' => 'startTlsEnabled',
        'startTlsRequired' => 'startTlsRequired',
        'sslOnConnectEnabled' => 'sslOnConnectEnabled',
        'sslServerIdentityCheckEnabled' => 'sslServerIdentityCheckEnabled',
        'nexusTrustStoreEnabled' => 'nexusTrustStoreEnabled'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'enabled' => 'setEnabled',
        'host' => 'setHost',
        'port' => 'setPort',
        'username' => 'setUsername',
        'password' => 'setPassword',
        'fromAddress' => 'setFromAddress',
        'subjectPrefix' => 'setSubjectPrefix',
        'startTlsEnabled' => 'setStartTlsEnabled',
        'startTlsRequired' => 'setStartTlsRequired',
        'sslOnConnectEnabled' => 'setSslOnConnectEnabled',
        'sslServerIdentityCheckEnabled' => 'setSslServerIdentityCheckEnabled',
        'nexusTrustStoreEnabled' => 'setNexusTrustStoreEnabled'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'enabled' => 'getEnabled',
        'host' => 'getHost',
        'port' => 'getPort',
        'username' => 'getUsername',
        'password' => 'getPassword',
        'fromAddress' => 'getFromAddress',
        'subjectPrefix' => 'getSubjectPrefix',
        'startTlsEnabled' => 'getStartTlsEnabled',
        'startTlsRequired' => 'getStartTlsRequired',
        'sslOnConnectEnabled' => 'getSslOnConnectEnabled',
        'sslServerIdentityCheckEnabled' => 'getSslServerIdentityCheckEnabled',
        'nexusTrustStoreEnabled' => 'getNexusTrustStoreEnabled'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['enabled'] = isset($data['enabled']) ? $data['enabled'] : null;
        $this->container['host'] = isset($data['host']) ? $data['host'] : null;
        $this->container['port'] = isset($data['port']) ? $data['port'] : null;
        $this->container['username'] = isset($data['username']) ? $data['username'] : null;
        $this->container['password'] = isset($data['password']) ? $data['password'] : null;
        $this->container['fromAddress'] = isset($data['fromAddress']) ? $data['fromAddress'] : null;
        $this->container['subjectPrefix'] = isset($data['subjectPrefix']) ? $data['subjectPrefix'] : null;
        $this->container['startTlsEnabled'] = isset($data['startTlsEnabled']) ? $data['startTlsEnabled'] : null;
        $this->container['startTlsRequired'] = isset($data['startTlsRequired']) ? $data['startTlsRequired'] : null;
        $this->container['sslOnConnectEnabled'] = isset($data['sslOnConnectEnabled']) ? $data['sslOnConnectEnabled'] : null;
        $this->container['sslServerIdentityCheckEnabled'] = isset($data['sslServerIdentityCheckEnabled']) ? $data['sslServerIdentityCheckEnabled'] : null;
        $this->container['nexusTrustStoreEnabled'] = isset($data['nexusTrustStoreEnabled']) ? $data['nexusTrustStoreEnabled'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['port'] === null) {
            $invalidProperties[] = "'port' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets enabled
     *
     * @return bool
     */
    public function getEnabled()
    {
        return $this->container['enabled'];
    }

    /**
     * Sets enabled
     *
     * @param bool $enabled enabled
     *
     * @return $this
     */
    public function setEnabled($enabled)
    {
        $this->container['enabled'] = $enabled;

        return $this;
    }

    /**
     * Gets host
     *
     * @return string
     */
    public function getHost()
    {
        return $this->container['host'];
    }

    /**
     * Sets host
     *
     * @param string $host host
     *
     * @return $this
     */
    public function setHost($host)
    {
        $this->container['host'] = $host;

        return $this;
    }

    /**
     * Gets port
     *
     * @return int
     */
    public function getPort()
    {
        return $this->container['port'];
    }

    /**
     * Sets port
     *
     * @param int $port port
     *
     * @return $this
     */
    public function setPort($port)
    {
        $this->container['port'] = $port;

        return $this;
    }

    /**
     * Gets username
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->container['username'];
    }

    /**
     * Sets username
     *
     * @param string $username username
     *
     * @return $this
     */
    public function setUsername($username)
    {
        $this->container['username'] = $username;

        return $this;
    }

    /**
     * Gets password
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->container['password'];
    }

    /**
     * Sets password
     *
     * @param string $password password
     *
     * @return $this
     */
    public function setPassword($password)
    {
        $this->container['password'] = $password;

        return $this;
    }

    /**
     * Gets fromAddress
     *
     * @return string
     */
    public function getFromAddress()
    {
        return $this->container['fromAddress'];
    }

    /**
     * Sets fromAddress
     *
     * @param string $fromAddress fromAddress
     *
     * @return $this
     */
    public function setFromAddress($fromAddress)
    {
        $this->container['fromAddress'] = $fromAddress;

        return $this;
    }

    /**
     * Gets subjectPrefix
     *
     * @return string
     */
    public function getSubjectPrefix()
    {
        return $this->container['subjectPrefix'];
    }

    /**
     * Sets subjectPrefix
     *
     * @param string $subjectPrefix A prefix to add to all email subjects to aid in identifying automated emails
     *
     * @return $this
     */
    public function setSubjectPrefix($subjectPrefix)
    {
        $this->container['subjectPrefix'] = $subjectPrefix;

        return $this;
    }

    /**
     * Gets startTlsEnabled
     *
     * @return bool
     */
    public function getStartTlsEnabled()
    {
        return $this->container['startTlsEnabled'];
    }

    /**
     * Sets startTlsEnabled
     *
     * @param bool $startTlsEnabled Enable STARTTLS Support for Insecure Connections
     *
     * @return $this
     */
    public function setStartTlsEnabled($startTlsEnabled)
    {
        $this->container['startTlsEnabled'] = $startTlsEnabled;

        return $this;
    }

    /**
     * Gets startTlsRequired
     *
     * @return bool
     */
    public function getStartTlsRequired()
    {
        return $this->container['startTlsRequired'];
    }

    /**
     * Sets startTlsRequired
     *
     * @param bool $startTlsRequired Require STARTTLS Support
     *
     * @return $this
     */
    public function setStartTlsRequired($startTlsRequired)
    {
        $this->container['startTlsRequired'] = $startTlsRequired;

        return $this;
    }

    /**
     * Gets sslOnConnectEnabled
     *
     * @return bool
     */
    public function getSslOnConnectEnabled()
    {
        return $this->container['sslOnConnectEnabled'];
    }

    /**
     * Sets sslOnConnectEnabled
     *
     * @param bool $sslOnConnectEnabled Enable SSL/TLS Encryption upon Connection
     *
     * @return $this
     */
    public function setSslOnConnectEnabled($sslOnConnectEnabled)
    {
        $this->container['sslOnConnectEnabled'] = $sslOnConnectEnabled;

        return $this;
    }

    /**
     * Gets sslServerIdentityCheckEnabled
     *
     * @return bool
     */
    public function getSslServerIdentityCheckEnabled()
    {
        return $this->container['sslServerIdentityCheckEnabled'];
    }

    /**
     * Sets sslServerIdentityCheckEnabled
     *
     * @param bool $sslServerIdentityCheckEnabled Verify the server certificate when using TLS or SSL
     *
     * @return $this
     */
    public function setSslServerIdentityCheckEnabled($sslServerIdentityCheckEnabled)
    {
        $this->container['sslServerIdentityCheckEnabled'] = $sslServerIdentityCheckEnabled;

        return $this;
    }

    /**
     * Gets nexusTrustStoreEnabled
     *
     * @return bool
     */
    public function getNexusTrustStoreEnabled()
    {
        return $this->container['nexusTrustStoreEnabled'];
    }

    /**
     * Sets nexusTrustStoreEnabled
     *
     * @param bool $nexusTrustStoreEnabled Use the Nexus Repository Manager's certificate truststore
     *
     * @return $this
     */
    public function setNexusTrustStoreEnabled($nexusTrustStoreEnabled)
    {
        $this->container['nexusTrustStoreEnabled'] = $nexusTrustStoreEnabled;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


