<?php
/**
 * HostedStorageAttributes
 *
 * PHP version 5
 *
 * @category Class
 * @package  Optimacros\NexusPhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.43.0-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Optimacros\NexusPhpApi\Model;

use \ArrayAccess;
use \Optimacros\NexusPhpApi\ObjectSerializer;

/**
 * HostedStorageAttributes Class Doc Comment
 *
 * @category Class
 * @package  Optimacros\NexusPhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class HostedStorageAttributes implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'HostedStorageAttributes';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'blobStoreName' => 'string',
        'strictContentTypeValidation' => 'bool',
        'writePolicy' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'blobStoreName' => null,
        'strictContentTypeValidation' => null,
        'writePolicy' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'blobStoreName' => 'blobStoreName',
        'strictContentTypeValidation' => 'strictContentTypeValidation',
        'writePolicy' => 'writePolicy'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'blobStoreName' => 'setBlobStoreName',
        'strictContentTypeValidation' => 'setStrictContentTypeValidation',
        'writePolicy' => 'setWritePolicy'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'blobStoreName' => 'getBlobStoreName',
        'strictContentTypeValidation' => 'getStrictContentTypeValidation',
        'writePolicy' => 'getWritePolicy'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const WRITE_POLICY_ALLOW = 'allow';
    const WRITE_POLICY_ALLOW_ONCE = 'allow_once';
    const WRITE_POLICY_DENY = 'deny';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getWritePolicyAllowableValues()
    {
        return [
            self::WRITE_POLICY_ALLOW,
            self::WRITE_POLICY_ALLOW_ONCE,
            self::WRITE_POLICY_DENY,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['blobStoreName'] = isset($data['blobStoreName']) ? $data['blobStoreName'] : null;
        $this->container['strictContentTypeValidation'] = isset($data['strictContentTypeValidation']) ? $data['strictContentTypeValidation'] : null;
        $this->container['writePolicy'] = isset($data['writePolicy']) ? $data['writePolicy'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['strictContentTypeValidation'] === null) {
            $invalidProperties[] = "'strictContentTypeValidation' can't be null";
        }
        if ($this->container['writePolicy'] === null) {
            $invalidProperties[] = "'writePolicy' can't be null";
        }
        $allowedValues = $this->getWritePolicyAllowableValues();
        if (!is_null($this->container['writePolicy']) && !in_array($this->container['writePolicy'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'writePolicy', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets blobStoreName
     *
     * @return string
     */
    public function getBlobStoreName()
    {
        return $this->container['blobStoreName'];
    }

    /**
     * Sets blobStoreName
     *
     * @param string $blobStoreName Blob store used to store repository contents
     *
     * @return $this
     */
    public function setBlobStoreName($blobStoreName)
    {
        $this->container['blobStoreName'] = $blobStoreName;

        return $this;
    }

    /**
     * Gets strictContentTypeValidation
     *
     * @return bool
     */
    public function getStrictContentTypeValidation()
    {
        return $this->container['strictContentTypeValidation'];
    }

    /**
     * Sets strictContentTypeValidation
     *
     * @param bool $strictContentTypeValidation Whether to validate uploaded content's MIME type appropriate for the repository format
     *
     * @return $this
     */
    public function setStrictContentTypeValidation($strictContentTypeValidation)
    {
        $this->container['strictContentTypeValidation'] = $strictContentTypeValidation;

        return $this;
    }

    /**
     * Gets writePolicy
     *
     * @return string
     */
    public function getWritePolicy()
    {
        return $this->container['writePolicy'];
    }

    /**
     * Sets writePolicy
     *
     * @param string $writePolicy Controls if deployments of and updates to assets are allowed
     *
     * @return $this
     */
    public function setWritePolicy($writePolicy)
    {
        $allowedValues = $this->getWritePolicyAllowableValues();
        if (!in_array($writePolicy, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'writePolicy', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['writePolicy'] = $writePolicy;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


