<?php
/**
 * IqConnectionXo
 *
 * PHP version 5
 *
 * @category Class
 * @package  Optimacros\NexusPhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.43.0-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Optimacros\NexusPhpApi\Model;

use \ArrayAccess;
use \Optimacros\NexusPhpApi\ObjectSerializer;

/**
 * IqConnectionXo Class Doc Comment
 *
 * @category Class
 * @package  Optimacros\NexusPhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class IqConnectionXo implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'IqConnectionXo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'enabled' => 'bool',
        'showLink' => 'bool',
        'url' => 'string',
        'authenticationType' => 'string',
        'username' => 'string',
        'password' => 'string',
        'useTrustStoreForUrl' => 'bool',
        'timeoutSeconds' => 'int',
        'properties' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'enabled' => null,
        'showLink' => null,
        'url' => null,
        'authenticationType' => null,
        'username' => null,
        'password' => null,
        'useTrustStoreForUrl' => null,
        'timeoutSeconds' => 'int32',
        'properties' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'enabled' => 'enabled',
        'showLink' => 'showLink',
        'url' => 'url',
        'authenticationType' => 'authenticationType',
        'username' => 'username',
        'password' => 'password',
        'useTrustStoreForUrl' => 'useTrustStoreForUrl',
        'timeoutSeconds' => 'timeoutSeconds',
        'properties' => 'properties'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'enabled' => 'setEnabled',
        'showLink' => 'setShowLink',
        'url' => 'setUrl',
        'authenticationType' => 'setAuthenticationType',
        'username' => 'setUsername',
        'password' => 'setPassword',
        'useTrustStoreForUrl' => 'setUseTrustStoreForUrl',
        'timeoutSeconds' => 'setTimeoutSeconds',
        'properties' => 'setProperties'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'enabled' => 'getEnabled',
        'showLink' => 'getShowLink',
        'url' => 'getUrl',
        'authenticationType' => 'getAuthenticationType',
        'username' => 'getUsername',
        'password' => 'getPassword',
        'useTrustStoreForUrl' => 'getUseTrustStoreForUrl',
        'timeoutSeconds' => 'getTimeoutSeconds',
        'properties' => 'getProperties'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const AUTHENTICATION_TYPE_USER = 'USER';
    const AUTHENTICATION_TYPE_PKI = 'PKI';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAuthenticationTypeAllowableValues()
    {
        return [
            self::AUTHENTICATION_TYPE_USER,
            self::AUTHENTICATION_TYPE_PKI,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['enabled'] = isset($data['enabled']) ? $data['enabled'] : null;
        $this->container['showLink'] = isset($data['showLink']) ? $data['showLink'] : null;
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
        $this->container['authenticationType'] = isset($data['authenticationType']) ? $data['authenticationType'] : null;
        $this->container['username'] = isset($data['username']) ? $data['username'] : null;
        $this->container['password'] = isset($data['password']) ? $data['password'] : null;
        $this->container['useTrustStoreForUrl'] = isset($data['useTrustStoreForUrl']) ? $data['useTrustStoreForUrl'] : null;
        $this->container['timeoutSeconds'] = isset($data['timeoutSeconds']) ? $data['timeoutSeconds'] : null;
        $this->container['properties'] = isset($data['properties']) ? $data['properties'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['authenticationType'] === null) {
            $invalidProperties[] = "'authenticationType' can't be null";
        }
        $allowedValues = $this->getAuthenticationTypeAllowableValues();
        if (!is_null($this->container['authenticationType']) && !in_array($this->container['authenticationType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'authenticationType', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['timeoutSeconds']) && ($this->container['timeoutSeconds'] > 3600)) {
            $invalidProperties[] = "invalid value for 'timeoutSeconds', must be smaller than or equal to 3600.";
        }

        if (!is_null($this->container['timeoutSeconds']) && ($this->container['timeoutSeconds'] < 1)) {
            $invalidProperties[] = "invalid value for 'timeoutSeconds', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets enabled
     *
     * @return bool
     */
    public function getEnabled()
    {
        return $this->container['enabled'];
    }

    /**
     * Sets enabled
     *
     * @param bool $enabled Whether to use IQ Server
     *
     * @return $this
     */
    public function setEnabled($enabled)
    {
        $this->container['enabled'] = $enabled;

        return $this;
    }

    /**
     * Gets showLink
     *
     * @return bool
     */
    public function getShowLink()
    {
        return $this->container['showLink'];
    }

    /**
     * Sets showLink
     *
     * @param bool $showLink Show IQ Server link in Browse menu when server is enabled
     *
     * @return $this
     */
    public function setShowLink($showLink)
    {
        $this->container['showLink'] = $showLink;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url The address of your IQ Server
     *
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets authenticationType
     *
     * @return string
     */
    public function getAuthenticationType()
    {
        return $this->container['authenticationType'];
    }

    /**
     * Sets authenticationType
     *
     * @param string $authenticationType Authentication method
     *
     * @return $this
     */
    public function setAuthenticationType($authenticationType)
    {
        $allowedValues = $this->getAuthenticationTypeAllowableValues();
        if (!in_array($authenticationType, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'authenticationType', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['authenticationType'] = $authenticationType;

        return $this;
    }

    /**
     * Gets username
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->container['username'];
    }

    /**
     * Sets username
     *
     * @param string $username User with access to IQ Server
     *
     * @return $this
     */
    public function setUsername($username)
    {
        $this->container['username'] = $username;

        return $this;
    }

    /**
     * Gets password
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->container['password'];
    }

    /**
     * Sets password
     *
     * @param string $password Credentials for the IQ Server User
     *
     * @return $this
     */
    public function setPassword($password)
    {
        $this->container['password'] = $password;

        return $this;
    }

    /**
     * Gets useTrustStoreForUrl
     *
     * @return bool
     */
    public function getUseTrustStoreForUrl()
    {
        return $this->container['useTrustStoreForUrl'];
    }

    /**
     * Sets useTrustStoreForUrl
     *
     * @param bool $useTrustStoreForUrl Use certificates stored in the Nexus Repository Manager truststore to connect to IQ Server
     *
     * @return $this
     */
    public function setUseTrustStoreForUrl($useTrustStoreForUrl)
    {
        $this->container['useTrustStoreForUrl'] = $useTrustStoreForUrl;

        return $this;
    }

    /**
     * Gets timeoutSeconds
     *
     * @return int
     */
    public function getTimeoutSeconds()
    {
        return $this->container['timeoutSeconds'];
    }

    /**
     * Sets timeoutSeconds
     *
     * @param int $timeoutSeconds Seconds to wait for activity before stopping and retrying the connection. Leave blank to use the globally defined HTTP timeout.
     *
     * @return $this
     */
    public function setTimeoutSeconds($timeoutSeconds)
    {

        if (!is_null($timeoutSeconds) && ($timeoutSeconds > 3600)) {
            throw new \InvalidArgumentException('invalid value for $timeoutSeconds when calling IqConnectionXo., must be smaller than or equal to 3600.');
        }
        if (!is_null($timeoutSeconds) && ($timeoutSeconds < 1)) {
            throw new \InvalidArgumentException('invalid value for $timeoutSeconds when calling IqConnectionXo., must be bigger than or equal to 1.');
        }

        $this->container['timeoutSeconds'] = $timeoutSeconds;

        return $this;
    }

    /**
     * Gets properties
     *
     * @return string
     */
    public function getProperties()
    {
        return $this->container['properties'];
    }

    /**
     * Sets properties
     *
     * @param string $properties Additional properties to configure for IQ Server
     *
     * @return $this
     */
    public function setProperties($properties)
    {
        $this->container['properties'] = $properties;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


