<?php
/**
 * YumAttributes
 *
 * PHP version 5
 *
 * @category Class
 * @package  Optimacros\NexusPhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.43.0-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Optimacros\NexusPhpApi\Model;

use \ArrayAccess;
use \Optimacros\NexusPhpApi\ObjectSerializer;

/**
 * YumAttributes Class Doc Comment
 *
 * @category Class
 * @package  Optimacros\NexusPhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class YumAttributes implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'YumAttributes';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'repodataDepth' => 'int',
        'deployPolicy' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'repodataDepth' => 'int32',
        'deployPolicy' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'repodataDepth' => 'repodataDepth',
        'deployPolicy' => 'deployPolicy'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'repodataDepth' => 'setRepodataDepth',
        'deployPolicy' => 'setDeployPolicy'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'repodataDepth' => 'getRepodataDepth',
        'deployPolicy' => 'getDeployPolicy'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const DEPLOY_POLICY_PERMISSIVE = 'PERMISSIVE';
    const DEPLOY_POLICY_STRICT = 'STRICT';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDeployPolicyAllowableValues()
    {
        return [
            self::DEPLOY_POLICY_PERMISSIVE,
            self::DEPLOY_POLICY_STRICT,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['repodataDepth'] = isset($data['repodataDepth']) ? $data['repodataDepth'] : null;
        $this->container['deployPolicy'] = isset($data['deployPolicy']) ? $data['deployPolicy'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['repodataDepth'] === null) {
            $invalidProperties[] = "'repodataDepth' can't be null";
        }
        if (($this->container['repodataDepth'] > 5)) {
            $invalidProperties[] = "invalid value for 'repodataDepth', must be smaller than or equal to 5.";
        }

        if (($this->container['repodataDepth'] < 0)) {
            $invalidProperties[] = "invalid value for 'repodataDepth', must be bigger than or equal to 0.";
        }

        $allowedValues = $this->getDeployPolicyAllowableValues();
        if (!is_null($this->container['deployPolicy']) && !in_array($this->container['deployPolicy'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'deployPolicy', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets repodataDepth
     *
     * @return int
     */
    public function getRepodataDepth()
    {
        return $this->container['repodataDepth'];
    }

    /**
     * Sets repodataDepth
     *
     * @param int $repodataDepth Specifies the repository depth where repodata folder(s) are created
     *
     * @return $this
     */
    public function setRepodataDepth($repodataDepth)
    {

        if (($repodataDepth > 5)) {
            throw new \InvalidArgumentException('invalid value for $repodataDepth when calling YumAttributes., must be smaller than or equal to 5.');
        }
        if (($repodataDepth < 0)) {
            throw new \InvalidArgumentException('invalid value for $repodataDepth when calling YumAttributes., must be bigger than or equal to 0.');
        }

        $this->container['repodataDepth'] = $repodataDepth;

        return $this;
    }

    /**
     * Gets deployPolicy
     *
     * @return string
     */
    public function getDeployPolicy()
    {
        return $this->container['deployPolicy'];
    }

    /**
     * Sets deployPolicy
     *
     * @param string $deployPolicy Validate that all paths are RPMs or yum metadata
     *
     * @return $this
     */
    public function setDeployPolicy($deployPolicy)
    {
        $allowedValues = $this->getDeployPolicyAllowableValues();
        if (!is_null($deployPolicy) && !in_array($deployPolicy, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'deployPolicy', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['deployPolicy'] = $deployPolicy;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


