<?php
/**
 * AzureBlobStoreApiBucketConfigurationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Optimacros\NexusPhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.43.0-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Optimacros\NexusPhpApi;

/**
 * AzureBlobStoreApiBucketConfigurationTest Class Doc Comment
 *
 * @category    Class
 * @description AzureBlobStoreApiBucketConfiguration
 * @package     Optimacros\NexusPhpApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AzureBlobStoreApiBucketConfigurationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AzureBlobStoreApiBucketConfiguration"
     */
    public function testAzureBlobStoreApiBucketConfiguration()
    {
    }

    /**
     * Test attribute "accountName"
     */
    public function testPropertyAccountName()
    {
    }

    /**
     * Test attribute "containerName"
     */
    public function testPropertyContainerName()
    {
    }

    /**
     * Test attribute "authentication"
     */
    public function testPropertyAuthentication()
    {
    }
}
