<?php
/**
 * S3BlobStoreApiBucketSecurityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Optimacros\NexusPhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.43.0-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Optimacros\NexusPhpApi;

/**
 * S3BlobStoreApiBucketSecurityTest Class Doc Comment
 *
 * @category    Class
 * @description S3BlobStoreApiBucketSecurity
 * @package     Optimacros\NexusPhpApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class S3BlobStoreApiBucketSecurityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "S3BlobStoreApiBucketSecurity"
     */
    public function testS3BlobStoreApiBucketSecurity()
    {
    }

    /**
     * Test attribute "accessKeyId"
     */
    public function testPropertyAccessKeyId()
    {
    }

    /**
     * Test attribute "secretAccessKey"
     */
    public function testPropertySecretAccessKey()
    {
    }

    /**
     * Test attribute "role"
     */
    public function testPropertyRole()
    {
    }

    /**
     * Test attribute "sessionToken"
     */
    public function testPropertySessionToken()
    {
    }
}
