<?php
/**
 * V1ComponentsBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Optimacros\NexusPhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.43.0-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Optimacros\NexusPhpApi;

/**
 * V1ComponentsBodyTest Class Doc Comment
 *
 * @category    Class
 * @description V1ComponentsBody
 * @package     Optimacros\NexusPhpApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1ComponentsBodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1ComponentsBody"
     */
    public function testV1ComponentsBody()
    {
    }

    /**
     * Test attribute "rAsset"
     */
    public function testPropertyRAsset()
    {
    }

    /**
     * Test attribute "rAssetPathId"
     */
    public function testPropertyRAssetPathId()
    {
    }

    /**
     * Test attribute "pypiAsset"
     */
    public function testPropertyPypiAsset()
    {
    }

    /**
     * Test attribute "helmAsset"
     */
    public function testPropertyHelmAsset()
    {
    }

    /**
     * Test attribute "yumDirectory"
     */
    public function testPropertyYumDirectory()
    {
    }

    /**
     * Test attribute "yumAsset"
     */
    public function testPropertyYumAsset()
    {
    }

    /**
     * Test attribute "yumAssetFilename"
     */
    public function testPropertyYumAssetFilename()
    {
    }

    /**
     * Test attribute "dockerAsset"
     */
    public function testPropertyDockerAsset()
    {
    }

    /**
     * Test attribute "rubygemsAsset"
     */
    public function testPropertyRubygemsAsset()
    {
    }

    /**
     * Test attribute "nugetAsset"
     */
    public function testPropertyNugetAsset()
    {
    }

    /**
     * Test attribute "npmAsset"
     */
    public function testPropertyNpmAsset()
    {
    }

    /**
     * Test attribute "rawDirectory"
     */
    public function testPropertyRawDirectory()
    {
    }

    /**
     * Test attribute "rawAsset1"
     */
    public function testPropertyRawAsset1()
    {
    }

    /**
     * Test attribute "rawAsset1Filename"
     */
    public function testPropertyRawAsset1Filename()
    {
    }

    /**
     * Test attribute "rawAsset2"
     */
    public function testPropertyRawAsset2()
    {
    }

    /**
     * Test attribute "rawAsset2Filename"
     */
    public function testPropertyRawAsset2Filename()
    {
    }

    /**
     * Test attribute "rawAsset3"
     */
    public function testPropertyRawAsset3()
    {
    }

    /**
     * Test attribute "rawAsset3Filename"
     */
    public function testPropertyRawAsset3Filename()
    {
    }

    /**
     * Test attribute "aptAsset"
     */
    public function testPropertyAptAsset()
    {
    }

    /**
     * Test attribute "maven2GroupId"
     */
    public function testPropertyMaven2GroupId()
    {
    }

    /**
     * Test attribute "maven2ArtifactId"
     */
    public function testPropertyMaven2ArtifactId()
    {
    }

    /**
     * Test attribute "maven2Version"
     */
    public function testPropertyMaven2Version()
    {
    }

    /**
     * Test attribute "maven2GeneratePom"
     */
    public function testPropertyMaven2GeneratePom()
    {
    }

    /**
     * Test attribute "maven2Packaging"
     */
    public function testPropertyMaven2Packaging()
    {
    }

    /**
     * Test attribute "maven2Asset1"
     */
    public function testPropertyMaven2Asset1()
    {
    }

    /**
     * Test attribute "maven2Asset1Classifier"
     */
    public function testPropertyMaven2Asset1Classifier()
    {
    }

    /**
     * Test attribute "maven2Asset1Extension"
     */
    public function testPropertyMaven2Asset1Extension()
    {
    }

    /**
     * Test attribute "maven2Asset2"
     */
    public function testPropertyMaven2Asset2()
    {
    }

    /**
     * Test attribute "maven2Asset2Classifier"
     */
    public function testPropertyMaven2Asset2Classifier()
    {
    }

    /**
     * Test attribute "maven2Asset2Extension"
     */
    public function testPropertyMaven2Asset2Extension()
    {
    }

    /**
     * Test attribute "maven2Asset3"
     */
    public function testPropertyMaven2Asset3()
    {
    }

    /**
     * Test attribute "maven2Asset3Classifier"
     */
    public function testPropertyMaven2Asset3Classifier()
    {
    }

    /**
     * Test attribute "maven2Asset3Extension"
     */
    public function testPropertyMaven2Asset3Extension()
    {
    }
}
