<?php
/**
 * RepositoryManagementApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Optimacros\NexusPhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.43.0-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Optimacros\NexusPhpApi;

use \Optimacros\NexusPhpApi\Configuration;
use \Optimacros\NexusPhpApi\ApiException;
use \Optimacros\NexusPhpApi\ObjectSerializer;

/**
 * RepositoryManagementApiTest Class Doc Comment
 *
 * @category Class
 * @package  Optimacros\NexusPhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RepositoryManagementApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createRepository
     *
     * Create Maven group repository.
     *
     */
    public function testCreateRepository()
    {
    }

    /**
     * Test case for createRepository1
     *
     * Create Maven hosted repository.
     *
     */
    public function testCreateRepository1()
    {
    }

    /**
     * Test case for createRepository10
     *
     * Create npm proxy repository.
     *
     */
    public function testCreateRepository10()
    {
    }

    /**
     * Test case for createRepository11
     *
     * Create NuGet group repository.
     *
     */
    public function testCreateRepository11()
    {
    }

    /**
     * Test case for createRepository12
     *
     * Create NuGet hosted repository.
     *
     */
    public function testCreateRepository12()
    {
    }

    /**
     * Test case for createRepository13
     *
     * Create NuGet proxy repository.
     *
     */
    public function testCreateRepository13()
    {
    }

    /**
     * Test case for createRepository14
     *
     * Create RubyGems group repository.
     *
     */
    public function testCreateRepository14()
    {
    }

    /**
     * Test case for createRepository15
     *
     * Create RubyGems hosted repository.
     *
     */
    public function testCreateRepository15()
    {
    }

    /**
     * Test case for createRepository16
     *
     * Create RubyGems proxy repository.
     *
     */
    public function testCreateRepository16()
    {
    }

    /**
     * Test case for createRepository17
     *
     * Create Docker group repository.
     *
     */
    public function testCreateRepository17()
    {
    }

    /**
     * Test case for createRepository18
     *
     * Create Docker hosted repository.
     *
     */
    public function testCreateRepository18()
    {
    }

    /**
     * Test case for createRepository19
     *
     * Create Docker proxy repository.
     *
     */
    public function testCreateRepository19()
    {
    }

    /**
     * Test case for createRepository2
     *
     * Create Maven proxy repository.
     *
     */
    public function testCreateRepository2()
    {
    }

    /**
     * Test case for createRepository20
     *
     * Create Yum group repository.
     *
     */
    public function testCreateRepository20()
    {
    }

    /**
     * Test case for createRepository21
     *
     * Create Yum hosted repository.
     *
     */
    public function testCreateRepository21()
    {
    }

    /**
     * Test case for createRepository22
     *
     * Create Yum proxy repository.
     *
     */
    public function testCreateRepository22()
    {
    }

    /**
     * Test case for createRepository23
     *
     * Create Helm hosted repository.
     *
     */
    public function testCreateRepository23()
    {
    }

    /**
     * Test case for createRepository24
     *
     * Create Helm proxy repository.
     *
     */
    public function testCreateRepository24()
    {
    }

    /**
     * Test case for createRepository25
     *
     * Create Git LFS hosted repository.
     *
     */
    public function testCreateRepository25()
    {
    }

    /**
     * Test case for createRepository26
     *
     * Create PyPI group repository.
     *
     */
    public function testCreateRepository26()
    {
    }

    /**
     * Test case for createRepository27
     *
     * Create PyPI hosted repository.
     *
     */
    public function testCreateRepository27()
    {
    }

    /**
     * Test case for createRepository28
     *
     * Create PyPI proxy repository.
     *
     */
    public function testCreateRepository28()
    {
    }

    /**
     * Test case for createRepository29
     *
     * Create conda proxy repository.
     *
     */
    public function testCreateRepository29()
    {
    }

    /**
     * Test case for createRepository3
     *
     * Create APT hosted repository.
     *
     */
    public function testCreateRepository3()
    {
    }

    /**
     * Test case for createRepository30
     *
     * Create Conan proxy repository.
     *
     */
    public function testCreateRepository30()
    {
    }

    /**
     * Test case for createRepository31
     *
     * Create R group repository.
     *
     */
    public function testCreateRepository31()
    {
    }

    /**
     * Test case for createRepository32
     *
     * Create R hosted repository.
     *
     */
    public function testCreateRepository32()
    {
    }

    /**
     * Test case for createRepository33
     *
     * Create R proxy repository.
     *
     */
    public function testCreateRepository33()
    {
    }

    /**
     * Test case for createRepository34
     *
     * Create Cocoapods proxy repository.
     *
     */
    public function testCreateRepository34()
    {
    }

    /**
     * Test case for createRepository35
     *
     * Create a Go group repository.
     *
     */
    public function testCreateRepository35()
    {
    }

    /**
     * Test case for createRepository36
     *
     * Create a Go proxy repository.
     *
     */
    public function testCreateRepository36()
    {
    }

    /**
     * Test case for createRepository37
     *
     * Create p2 proxy repository.
     *
     */
    public function testCreateRepository37()
    {
    }

    /**
     * Test case for createRepository38
     *
     * Create Bower group repository.
     *
     */
    public function testCreateRepository38()
    {
    }

    /**
     * Test case for createRepository39
     *
     * Create Bower hosted repository.
     *
     */
    public function testCreateRepository39()
    {
    }

    /**
     * Test case for createRepository4
     *
     * Create APT proxy repository.
     *
     */
    public function testCreateRepository4()
    {
    }

    /**
     * Test case for createRepository40
     *
     * Create Bower proxy repository.
     *
     */
    public function testCreateRepository40()
    {
    }

    /**
     * Test case for createRepository5
     *
     * Create raw group repository.
     *
     */
    public function testCreateRepository5()
    {
    }

    /**
     * Test case for createRepository6
     *
     * Create raw hosted repository.
     *
     */
    public function testCreateRepository6()
    {
    }

    /**
     * Test case for createRepository7
     *
     * Create raw proxy repository.
     *
     */
    public function testCreateRepository7()
    {
    }

    /**
     * Test case for createRepository8
     *
     * Create npm group repository.
     *
     */
    public function testCreateRepository8()
    {
    }

    /**
     * Test case for createRepository9
     *
     * Create npm hosted repository.
     *
     */
    public function testCreateRepository9()
    {
    }

    /**
     * Test case for deleteRepository
     *
     * Delete repository of any format.
     *
     */
    public function testDeleteRepository()
    {
    }

    /**
     * Test case for disableRepositoryHealthCheck
     *
     * Disable repository health check. Proxy repositories only..
     *
     */
    public function testDisableRepositoryHealthCheck()
    {
    }

    /**
     * Test case for enableRepositoryHealthCheck
     *
     * Enable repository health check. Proxy repositories only..
     *
     */
    public function testEnableRepositoryHealthCheck()
    {
    }

    /**
     * Test case for getRepositories
     *
     * List repositories.
     *
     */
    public function testGetRepositories()
    {
    }

    /**
     * Test case for getRepositories1
     *
     * List repositories.
     *
     */
    public function testGetRepositories1()
    {
    }

    /**
     * Test case for getRepository
     *
     * Get repository details.
     *
     */
    public function testGetRepository()
    {
    }

    /**
     * Test case for getRepository1
     *
     * Get repository.
     *
     */
    public function testGetRepository1()
    {
    }

    /**
     * Test case for getRepository10
     *
     * Get repository.
     *
     */
    public function testGetRepository10()
    {
    }

    /**
     * Test case for getRepository11
     *
     * Get repository.
     *
     */
    public function testGetRepository11()
    {
    }

    /**
     * Test case for getRepository12
     *
     * Get repository.
     *
     */
    public function testGetRepository12()
    {
    }

    /**
     * Test case for getRepository13
     *
     * Get repository.
     *
     */
    public function testGetRepository13()
    {
    }

    /**
     * Test case for getRepository14
     *
     * Get repository.
     *
     */
    public function testGetRepository14()
    {
    }

    /**
     * Test case for getRepository15
     *
     * Get repository.
     *
     */
    public function testGetRepository15()
    {
    }

    /**
     * Test case for getRepository16
     *
     * Get repository.
     *
     */
    public function testGetRepository16()
    {
    }

    /**
     * Test case for getRepository17
     *
     * Get repository.
     *
     */
    public function testGetRepository17()
    {
    }

    /**
     * Test case for getRepository18
     *
     * Get repository.
     *
     */
    public function testGetRepository18()
    {
    }

    /**
     * Test case for getRepository19
     *
     * Get repository.
     *
     */
    public function testGetRepository19()
    {
    }

    /**
     * Test case for getRepository2
     *
     * Get repository.
     *
     */
    public function testGetRepository2()
    {
    }

    /**
     * Test case for getRepository20
     *
     * Get repository.
     *
     */
    public function testGetRepository20()
    {
    }

    /**
     * Test case for getRepository21
     *
     * Get repository.
     *
     */
    public function testGetRepository21()
    {
    }

    /**
     * Test case for getRepository22
     *
     * Get repository.
     *
     */
    public function testGetRepository22()
    {
    }

    /**
     * Test case for getRepository23
     *
     * Get repository.
     *
     */
    public function testGetRepository23()
    {
    }

    /**
     * Test case for getRepository24
     *
     * Get repository.
     *
     */
    public function testGetRepository24()
    {
    }

    /**
     * Test case for getRepository25
     *
     * Get repository.
     *
     */
    public function testGetRepository25()
    {
    }

    /**
     * Test case for getRepository26
     *
     * Get repository.
     *
     */
    public function testGetRepository26()
    {
    }

    /**
     * Test case for getRepository27
     *
     * Get repository.
     *
     */
    public function testGetRepository27()
    {
    }

    /**
     * Test case for getRepository28
     *
     * Get repository.
     *
     */
    public function testGetRepository28()
    {
    }

    /**
     * Test case for getRepository29
     *
     * Get repository.
     *
     */
    public function testGetRepository29()
    {
    }

    /**
     * Test case for getRepository3
     *
     * Get repository.
     *
     */
    public function testGetRepository3()
    {
    }

    /**
     * Test case for getRepository30
     *
     * Get repository.
     *
     */
    public function testGetRepository30()
    {
    }

    /**
     * Test case for getRepository31
     *
     * Get repository.
     *
     */
    public function testGetRepository31()
    {
    }

    /**
     * Test case for getRepository32
     *
     * Get repository.
     *
     */
    public function testGetRepository32()
    {
    }

    /**
     * Test case for getRepository33
     *
     * Get repository.
     *
     */
    public function testGetRepository33()
    {
    }

    /**
     * Test case for getRepository34
     *
     * Get repository.
     *
     */
    public function testGetRepository34()
    {
    }

    /**
     * Test case for getRepository35
     *
     * Get repository.
     *
     */
    public function testGetRepository35()
    {
    }

    /**
     * Test case for getRepository36
     *
     * Get repository.
     *
     */
    public function testGetRepository36()
    {
    }

    /**
     * Test case for getRepository37
     *
     * Get repository.
     *
     */
    public function testGetRepository37()
    {
    }

    /**
     * Test case for getRepository38
     *
     * Get repository.
     *
     */
    public function testGetRepository38()
    {
    }

    /**
     * Test case for getRepository39
     *
     * Get repository.
     *
     */
    public function testGetRepository39()
    {
    }

    /**
     * Test case for getRepository4
     *
     * Get repository.
     *
     */
    public function testGetRepository4()
    {
    }

    /**
     * Test case for getRepository40
     *
     * Get repository.
     *
     */
    public function testGetRepository40()
    {
    }

    /**
     * Test case for getRepository41
     *
     * Get repository.
     *
     */
    public function testGetRepository41()
    {
    }

    /**
     * Test case for getRepository5
     *
     * Get repository.
     *
     */
    public function testGetRepository5()
    {
    }

    /**
     * Test case for getRepository6
     *
     * Get repository.
     *
     */
    public function testGetRepository6()
    {
    }

    /**
     * Test case for getRepository7
     *
     * Get repository.
     *
     */
    public function testGetRepository7()
    {
    }

    /**
     * Test case for getRepository8
     *
     * Get repository.
     *
     */
    public function testGetRepository8()
    {
    }

    /**
     * Test case for getRepository9
     *
     * Get repository.
     *
     */
    public function testGetRepository9()
    {
    }

    /**
     * Test case for invalidateCache
     *
     * Invalidate repository cache. Proxy or group repositories only..
     *
     */
    public function testInvalidateCache()
    {
    }

    /**
     * Test case for rebuildIndex
     *
     * Schedule a 'Repair - Rebuild repository search' Task. Hosted or proxy repositories only..
     *
     */
    public function testRebuildIndex()
    {
    }

    /**
     * Test case for updateRepository
     *
     * Update Maven group repository.
     *
     */
    public function testUpdateRepository()
    {
    }

    /**
     * Test case for updateRepository1
     *
     * Update Maven hosted repository.
     *
     */
    public function testUpdateRepository1()
    {
    }

    /**
     * Test case for updateRepository10
     *
     * Update npm proxy repository.
     *
     */
    public function testUpdateRepository10()
    {
    }

    /**
     * Test case for updateRepository11
     *
     * Update NuGet group repository.
     *
     */
    public function testUpdateRepository11()
    {
    }

    /**
     * Test case for updateRepository12
     *
     * Update NuGet hosted repository.
     *
     */
    public function testUpdateRepository12()
    {
    }

    /**
     * Test case for updateRepository13
     *
     * Update NuGet proxy repository.
     *
     */
    public function testUpdateRepository13()
    {
    }

    /**
     * Test case for updateRepository14
     *
     * Update RubyGems group repository.
     *
     */
    public function testUpdateRepository14()
    {
    }

    /**
     * Test case for updateRepository15
     *
     * Update RubyGems hosted repository.
     *
     */
    public function testUpdateRepository15()
    {
    }

    /**
     * Test case for updateRepository16
     *
     * Update RubyGems proxy repository.
     *
     */
    public function testUpdateRepository16()
    {
    }

    /**
     * Test case for updateRepository17
     *
     * Update Docker group repository.
     *
     */
    public function testUpdateRepository17()
    {
    }

    /**
     * Test case for updateRepository18
     *
     * Update Docker hosted repository.
     *
     */
    public function testUpdateRepository18()
    {
    }

    /**
     * Test case for updateRepository19
     *
     * Update Docker group repository.
     *
     */
    public function testUpdateRepository19()
    {
    }

    /**
     * Test case for updateRepository2
     *
     * Update Maven proxy repository.
     *
     */
    public function testUpdateRepository2()
    {
    }

    /**
     * Test case for updateRepository20
     *
     * Update Yum group repository.
     *
     */
    public function testUpdateRepository20()
    {
    }

    /**
     * Test case for updateRepository21
     *
     * Update Yum hosted repository.
     *
     */
    public function testUpdateRepository21()
    {
    }

    /**
     * Test case for updateRepository22
     *
     * Update Yum proxy repository.
     *
     */
    public function testUpdateRepository22()
    {
    }

    /**
     * Test case for updateRepository23
     *
     * Update Helm hosted repository.
     *
     */
    public function testUpdateRepository23()
    {
    }

    /**
     * Test case for updateRepository24
     *
     * Update Helm proxy repository.
     *
     */
    public function testUpdateRepository24()
    {
    }

    /**
     * Test case for updateRepository25
     *
     * Update Git LFS hosted repository.
     *
     */
    public function testUpdateRepository25()
    {
    }

    /**
     * Test case for updateRepository26
     *
     * Update PyPI group repository.
     *
     */
    public function testUpdateRepository26()
    {
    }

    /**
     * Test case for updateRepository27
     *
     * Update PyPI hosted repository.
     *
     */
    public function testUpdateRepository27()
    {
    }

    /**
     * Test case for updateRepository28
     *
     * Update PyPI proxy repository.
     *
     */
    public function testUpdateRepository28()
    {
    }

    /**
     * Test case for updateRepository29
     *
     * Update conda proxy repository.
     *
     */
    public function testUpdateRepository29()
    {
    }

    /**
     * Test case for updateRepository3
     *
     * Update APT hosted repository.
     *
     */
    public function testUpdateRepository3()
    {
    }

    /**
     * Test case for updateRepository30
     *
     * Update Conan proxy repository.
     *
     */
    public function testUpdateRepository30()
    {
    }

    /**
     * Test case for updateRepository31
     *
     * Update R group repository.
     *
     */
    public function testUpdateRepository31()
    {
    }

    /**
     * Test case for updateRepository32
     *
     * Update R hosted repository.
     *
     */
    public function testUpdateRepository32()
    {
    }

    /**
     * Test case for updateRepository33
     *
     * Update R proxy repository.
     *
     */
    public function testUpdateRepository33()
    {
    }

    /**
     * Test case for updateRepository34
     *
     * Update Cocoapods proxy repository.
     *
     */
    public function testUpdateRepository34()
    {
    }

    /**
     * Test case for updateRepository35
     *
     * Update a Go group repository.
     *
     */
    public function testUpdateRepository35()
    {
    }

    /**
     * Test case for updateRepository36
     *
     * Update a Go proxy repository.
     *
     */
    public function testUpdateRepository36()
    {
    }

    /**
     * Test case for updateRepository37
     *
     * Update p2 proxy repository.
     *
     */
    public function testUpdateRepository37()
    {
    }

    /**
     * Test case for updateRepository38
     *
     * Update Bower group repository.
     *
     */
    public function testUpdateRepository38()
    {
    }

    /**
     * Test case for updateRepository39
     *
     * Update Bower hosted repository.
     *
     */
    public function testUpdateRepository39()
    {
    }

    /**
     * Test case for updateRepository4
     *
     * Update APT proxy repository.
     *
     */
    public function testUpdateRepository4()
    {
    }

    /**
     * Test case for updateRepository40
     *
     * Update Bower proxy repository.
     *
     */
    public function testUpdateRepository40()
    {
    }

    /**
     * Test case for updateRepository5
     *
     * Update raw group repository.
     *
     */
    public function testUpdateRepository5()
    {
    }

    /**
     * Test case for updateRepository6
     *
     * Update raw hosted repository.
     *
     */
    public function testUpdateRepository6()
    {
    }

    /**
     * Test case for updateRepository7
     *
     * Update raw proxy repository.
     *
     */
    public function testUpdateRepository7()
    {
    }

    /**
     * Test case for updateRepository8
     *
     * Update npm group repository.
     *
     */
    public function testUpdateRepository8()
    {
    }

    /**
     * Test case for updateRepository9
     *
     * Update npm hosted repository.
     *
     */
    public function testUpdateRepository9()
    {
    }
}
