<?php
/**
 * SecurityManagementRolesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Optimacros\NexusPhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.43.0-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Optimacros\NexusPhpApi;

use \Optimacros\NexusPhpApi\Configuration;
use \Optimacros\NexusPhpApi\ApiException;
use \Optimacros\NexusPhpApi\ObjectSerializer;

/**
 * SecurityManagementRolesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Optimacros\NexusPhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SecurityManagementRolesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for create
     *
     * Create role.
     *
     */
    public function testCreate()
    {
    }

    /**
     * Test case for delete
     *
     * Delete role.
     *
     */
    public function testDelete()
    {
    }

    /**
     * Test case for getRole
     *
     * Get role.
     *
     */
    public function testGetRole()
    {
    }

    /**
     * Test case for getRoles
     *
     * List roles.
     *
     */
    public function testGetRoles()
    {
    }

    /**
     * Test case for update1
     *
     * Update role.
     *
     */
    public function testUpdate1()
    {
    }
}
