<?php
/**
 * SecurityManagementLDAPApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Optimacros\NexusPhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.43.0-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Optimacros\NexusPhpApi;

use \Optimacros\NexusPhpApi\Configuration;
use \Optimacros\NexusPhpApi\ApiException;
use \Optimacros\NexusPhpApi\ObjectSerializer;

/**
 * SecurityManagementLDAPApiTest Class Doc Comment
 *
 * @category Class
 * @package  Optimacros\NexusPhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SecurityManagementLDAPApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for changeOrder
     *
     * Change LDAP server order.
     *
     */
    public function testChangeOrder()
    {
    }

    /**
     * Test case for createLdapServer
     *
     * Create LDAP server.
     *
     */
    public function testCreateLdapServer()
    {
    }

    /**
     * Test case for deleteLdapServer
     *
     * Delete LDAP server.
     *
     */
    public function testDeleteLdapServer()
    {
    }

    /**
     * Test case for getLdapServer
     *
     * Get LDAP server.
     *
     */
    public function testGetLdapServer()
    {
    }

    /**
     * Test case for getLdapServers
     *
     * List LDAP servers.
     *
     */
    public function testGetLdapServers()
    {
    }

    /**
     * Test case for updateLdapServer
     *
     * Update LDAP server.
     *
     */
    public function testUpdateLdapServer()
    {
    }
}
