<?php
/**
 * StatusApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Optimacros\NexusPhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.43.0-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Optimacros\NexusPhpApi;

use \Optimacros\NexusPhpApi\Configuration;
use \Optimacros\NexusPhpApi\ApiException;
use \Optimacros\NexusPhpApi\ObjectSerializer;

/**
 * StatusApiTest Class Doc Comment
 *
 * @category Class
 * @package  Optimacros\NexusPhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class StatusApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getSystemStatusChecks
     *
     * Health check endpoint that returns the results of the system status checks.
     *
     */
    public function testGetSystemStatusChecks()
    {
    }

    /**
     * Test case for isAvailable
     *
     * Health check endpoint that validates server can respond to read requests.
     *
     */
    public function testIsAvailable()
    {
    }

    /**
     * Test case for isWritable
     *
     * Health check endpoint that validates server can respond to read and write requests.
     *
     */
    public function testIsWritable()
    {
    }
}
